c = [
    "driver/bus_driver.c",
    "driver/device_driver.c",
    "driver/device_manager.c",
    "driver/device.c",
    "driver/dma.c",
    "driver/driver_interface.c",
    "driver/driver.c",
    "app.c",
    "block_cache.c",
    "condvar.c",
    "console.c",
    "elf.c",
    "fifo.c",
    "font-default.c",
    "initcall.c",
    "main.c",
    "memory.c",
    "memtest.c",
    "periodic_task.c",
    "process.c",
    "rwlock.c",
    "softirq.c",
    "sync.c",
    "syscall.c",
    "thread.c",
    "wait_queue.c",
]
