c = [
    "driver/bus_driver.c",
    "driver/device_driver.c",
    "driver/device_manager.c",
    "driver/device.c",
    "driver/driver_interface.c",
    "driver/driver.c",
    "app.c",
    "block_cache.c",
    "console.c",
    "elf.c",
    "fifo.c",
    "font-default.c",
    "initcall.c",
    "main.c",
    "memory.c",
    "memtest.c",
    "periodic_task.c",
    "rwlock.c",
    "softirq.c",
    "syscall.c",
]
rust = ["thread/mod.rs", "interrupt/mod.rs", "memory/mod.rs", "topology/mod.rs"]
