arch = "x86_64"

[tools.macos]
cc = "x86_64-elf-gcc"
ld = "ld.lld"
ldflags = ["-flavor", "gnu", "-m", "elf_x86_64", "-nostdlib"]

[tools]
cc = "gcc"
as = "nasm"
ld = "ld"
cflags = [
    "-march=x86-64",
    "-mcmodel=large",
    "-std=gnu11",
    "-nostdinc",
    "-nostdlib",
    "-m64",
    "-mno-sse",
    "-mno-sse2",
    "-mno-mmx",
    "-mgeneral-regs-only",
    "-mno-red-zone",
    "-ffreestanding",
    "-fno-pie",
    "-fno-stack-protector",
    "-fno-strict-aliasing",
    "-fno-builtin",
    "-Wall",
    "-Wunused",
]
asflags = ["-f", "elf64"]
ldflags = ["-m", "elf_x86_64", "-nostdlib"]
rust_target = "x86_64-unknown-none"
rustflags = [
    "-C",
    "relocation-model=static",
    "--emit",
    "obj",
    "-C",
    "code-model=kernel",
    "-C",
    "symbol-mangling-version=v0",
    "-C",
    "force-frame-pointers=yes",
    "-C",
    "force-unwind-tables=no",
    "-C",
    "target-cpu=x86-64",
    "-C",
    "llvm-args=-vectorize-loops=false",
    "-C",
    "llvm-args=-vectorize-slp=false",
    "-Cllvm-args=--inline-threshold=0",
    # "--cfg",
    # "feature=\"slub_debug\"",
]

[debug]
level = "all"
cflags = ["-O0", "-g"]
asflags = ["-g"]
