sinclude ../scripts/env.mk
sinclude ../scripts/localenv.mk

X_ASFLAGS	:=	$(ENV_AFLAGS)
X_CFLAGS	:=	$(ENV_CFLAGS)

X_LDFLAGS	:=	$(ENV_LDFLAGS)
X_INCDIRS	:= ../include/

LD			:=	$(ENV_LD)
AS			:=	$(ENV_AS)
export AS LD

SRC			:=	syscall.c

TARGET_TYPE	:=	static
NAME		:=	sys