#ifndef _ATA_CMD_H
#define _ATA_CMD_H

#define ATA_CMD_CFA_ERASE_SECTORS				 0xc0
#define ATA_CMD_CFA_REQUEST_EXTENDED_ERROR		 0x03
#define ATA_CMD_CFA_TRANSLATE_SECTOR			 0x87
#define ATA_CMD_CFA_WRITE_MULTIPLE_WITHOUT_ERASE 0xcd
#define ATA_CMD_CFA_WRITE_SECTORS_WITHOUT_ERASE	 0x38

#define ATA_CMD_CHECK_MEDIA_CARD_TYPE 0xd1
#define ATA_CMD_CHECK_POWER_MODE	  0xe5

#define ATA_CMD_CONFIG_STREAM	   0x51
#define ATA_CMD_CONFIG_FREEZE_LOCK 0xb1
#define ATA_CMD_CONFIG_IDENTIFY	   0xb1
#define ATA_CMD_CONFIG_RESTORE	   0xb1
#define ATA_CMD_CONFIG_SET		   0xb1

#define ATA_CMD_DEVICE_RESET		   0x08
#define ATA_CMD_DOWNLOAD_MICROCODE	   0x92
#define ATA_CMD_EXEC_DEVICE_DIAGNOSTIC 0x90

#define ATA_CMD_FLUSH_CACHE		0xe7
#define ATA_CMD_FLUSH_CACHE_EXT 0xea

#define ATA_CMD_GET_MEDIA_STATUS  0xda
#define ATA_CMD_MEDIA_EJECT		  0xed
#define ATA_CMD_MEDIA_LOCK		  0xde
#define ATA_CMD_MEDIA_UNLOCK	  0xdf
#define ATA_CMD_STANDBY_IMMEDIATE 0xe0
#define ATA_CMD_IDLE_IMMEDIATE	  0xe1
#define ATA_CMD_STANDBY			  0xe2
#define ATA_CMD_IDLE			  0xe3

#define ATA_CMD_NOP					   0x00
#define ATA_CMD_SLEEP				   0xe6
#define ATA_CMD_IDENTIFY_DEVICE		   0xec
#define ATA_CMD_IDENTIFY_PACKET_DEVICE 0xa1
#define ATA_CMD_SET_FEATURES		   0xef
#define ATA_CMD_PACKET				   0xa0
#define ATA_CMD_SERVICE				   0xa2

#define ATA_CMD_READ_BUFFER				0xe4
#define ATA_CMD_READ_PIO				0x20
#define ATA_CMD_READ_PIO_EXT			0x24
#define ATA_CMD_READ_DMA				0xc8
#define ATA_CMD_READ_DMA_EXT			0x25
#define ATA_CMD_READ_DMA_QUEUED			0xc7
#define ATA_CMD_READ_DMA_QUEUED_EXT		0x26
#define ATA_CMD_READ_STREAM_DMA_EXT		0x2a
#define ATA_CMD_READ_STREAM_EXT			0x2b
#define ATA_CMD_READ_VERIFY_SECTORS		0x40
#define ATA_CMD_READ_VERIFY_SECTORS_EXT 0x42

#define ATA_CMD_WRITE_BUFFER		   0xe8
#define ATA_CMD_WRITE_PIO			   0x30
#define ATA_CMD_WRITE_PIO_EXT		   0x34
#define ATA_CMD_WRITE_DMA			   0xca
#define ATA_CMD_WRITE_DMA_EXT		   0x35
#define ATA_CMD_WRITE_DMA_QUEUED	   0xcc
#define ATA_CMD_WRITE_DMA_QUEUED_EXT   0x36
#define ATA_CMD_WRITE_DMA_MAX_ADDR_EXT 0x37
#define ATA_CMD_WRITE_STREAM_DMA_EXT   0x3a
#define ATA_CMD_WRITE_STREAM_EXT	   0x3b

#define ATA_CMD_READ_NATIVE_MAX_ADDR	 0xf8
#define ATA_CMD_READ_NATIVE_MAX_ADDR_EXT 0x27
#define ATA_CMD_SET_MAX_ADDR			 0xf9

#define ATA_CMD_READ_LOG_EXT  0x2f
#define ATA_CMD_WRITE_LOG_EXT 0x3f

#define ATA_CMD_WRITE_DMA_FUA_EXT		 0x3d
#define ATA_CMD_WRITE_DMA_QUEUED_FUA_EXT 0x3e
#define ATA_CMD_WRITE_FUA				 0xce

#define ATA_CMD_SET_MULTIPLE_MODE  0xc6
#define ATA_CMD_READ_MULTIPLE	   0xc4
#define ATA_CMD_READ_MULTIPLE_EXT  0x29
#define ATA_CMD_WRITE_MULTIPLE	   0xc5
#define ATA_CMD_WRITE_MULTIPLE_EXT 0x39

#define ATA_CMD_SECURITY_SET_PASSWORD	  0xf1
#define ATA_CMD_SECURITY_UNLOCK			  0xf2
#define ATA_CMD_SECURITY_ERASE_PREPARE	  0xf3
#define ATA_CMD_SECURITY_ERASE_UNIT		  0xf4
#define ATA_CMD_SECURITY_FREEZE_LOCK	  0xf5
#define ATA_CMD_SECURITY_DISABLE_PASSWORD 0xf6

#define ATA_CMD_SMART_DISABLE_OPERATIONS		0xb0
#define ATA_CMD_SMART_EN_DIS_AUTOSAVE			0xb0
#define ATA_CMD_SMART_ENABLE_OPERATIONS			0xb0
#define ATA_CMD_SMART_EXECUTE_OFFLINE_IMMEDIATE 0xb0
#define ATA_CMD_SMART_READ_DATA					0xb0
#define ATA_CMD_SMART_READ_LOG					0xb0
#define ATA_CMD_SMART_RETURN_STATUS				0xb0
#define ATA_CMD_SMART_WRITE_LOG					0xb0

#endif