#ifndef _BIOS_EMU_PREFIX_H
#define _BIOS_EMU_PREFIX_H

typedef enum BiosEmuPrefixs {
	PREFIX_LOCK			   = 0xF0,
	PREFIX_REPNE_REPNZ_BND = 0xF2,
	PREFIX_REP_REPE_REPZ   = 0xF3,

	PREFIX_CS_OVERRIDE_BRANCH_NOT_TAKEN = 0x2E,
	PREFIX_SS_OVERRIDE					= 0x36,
	PREFIX_DS_OVERRIDE_BRANCH_TAKEN		= 0x3E,
	PREFIX_ES_OVERRIDE					= 0x26,
	PREFIX_FS_OVERRIDE					= 0x64,
	PREFIX_GS_OVERRIDE					= 0x65,

	PREFIX_OPERAND_SIZE_OVERRIDE = 0x66,
	PREFIX_ADDRSIZE_OVERRIDE	 = 0x67,
} BiosEmuPrefixes;

#endif