name: C/C++ CI

on:
  push:
    branches: 
      - "master"
      - "GUI"
  pull_request:
    branches:
      - "master"
      - "GUI"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ilammy/setup-nasm@v1.4.0
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - uses: actions/setup-python@v5.3.0
    - name: make tools
      run: make tools
    - name: Generate Virtual Hard Disk with Grub
      run: make hd
    - name: Generate Virtual HD image with OS
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: horizon
        path: ${{ github.workspace }}
